-- PostgreSQL. Also represented by IncomingWhatsappMessage for existing ddl-auto:update installations.
CREATE TABLE IF NOT EXISTS whatsapp_inbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id VARCHAR(255) NOT NULL,
    message_id VARCHAR(255) NOT NULL,
    chat_id VARCHAR(255) NOT NULL,
    sender_name VARCHAR(255),
    text TEXT,
    message_type VARCHAR(255),
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    CONSTRAINT uc_whatsapp_inbox_message UNIQUE (instance_id, message_id)
);
CREATE INDEX IF NOT EXISTS idx_whatsapp_inbox_chat ON whatsapp_inbox(instance_id, chat_id, id);
