### GET QR CODE
GET http://localhost:9090/waInstance{{whatsappInstance}}/qrCode/{{whatsappToken}}

### USER STATE
GET http://localhost:9090/waInstance{{whatsappInstance}}/getStateInstance/{{whatsappToken}}

### USER SETTINGS
GET http://localhost:9090/waInstance{{whatsappInstance}}/getSettings/{{whatsappToken}}

### LOGOUT
GET http://localhost:9090/waInstance{{whatsappInstance}}/logout/{{whatsappToken}}

###       -> Simulate phone scanned QR
GET http://localhost:9090/mock/trigger-scan

###  -> Simulate 'alreadyLogged' with stranger phone
GET http://localhost:9090/mock/trigger-collision

### -> Reset mock state
GET http://localhost:9090/mock/reset