app:
  url:
    greenApi:
      url:
        greenBase: http://localhost:9090/waInstance
        qrCode:    ${app.url.greenApi.url.greenBase}{instanceId}/qrCode/{token}
        settings:  ${app.url.greenApi.url.greenBase}{instanceId}/getSettings/{token}
        logout:    ${app.url.greenApi.url.greenBase}{instanceId}/logout/{token}
        state:     ${app.url.greenApi.url.greenBase}{instanceId}/getStateInstance/{token}
        sendMessage: ${app.url.greenApi.url.greenBase}{instanceId}/sendMessage/{token}