package az.nizami.smartdirectaze.ai.controller;

import az.nizami.smartdirectaze.ai.AiService;
import az.nizami.smartdirectaze.identity.UserService;
import az.nizami.smartdirectaze.shop.ProductService;
import az.nizami.smartdirectaze.util.WhatsappTextUtils;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

/**
 * Lets the merchant talk to his AI seller in the browser, before connecting WhatsApp.
 */
@RestController
@RequestMapping("/api/v1/shops/{shopId}/ai/test-chat")
@RequiredArgsConstructor
@Log4j2
public class AiTestChatController {

    private final AiService aiService;
    private final ProductService productService;
    private final UserService userService;

    /**
     * @param sessionId generated by the page; a new one starts a conversation from scratch
     */
    public record TestChatRequest(@NotBlank @Size(max = 500) String message,
                                  @NotBlank @Size(max = 64) String sessionId) {
    }

    /**
     * @param reply formatted the same way as the WhatsApp message the customer gets
     */
    public record TestChatResponse(String reply) {
    }

    @PostMapping
    public ResponseEntity<TestChatResponse> chat(@PathVariable Long shopId,
                                                 @Valid @RequestBody TestChatRequest request,
                                                 @AuthenticationPrincipal UserDetails userDetails) {
        Long userId = verifyOwnership(shopId, userDetails);
        log.debug("Test chat of shop [{}], session [{}]", shopId, request.sessionId());

        String conversationId = "web:" + userId + ":" + request.sessionId();
        String reply = aiService.answer(shopId, conversationId, null, request.message());
        return ResponseEntity.ok(new TestChatResponse(WhatsappTextUtils.convertMdToWhatsapp(reply)));
    }

    /**
     * Returns the current user id; 404 for a foreign shop, so its existence is not revealed.
     */
    private Long verifyOwnership(Long shopId, UserDetails userDetails) {
        if (userDetails == null) {
            throw new ResponseStatusException(HttpStatus.UNAUTHORIZED, "Not authenticated");
        }
        Long userId = userService.findByEmail(userDetails.getUsername())
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.UNAUTHORIZED, "User not found"))
                .getId();
        if (!productService.isShopBelongToUser(shopId, userId)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Shop not found");
        }
        return userId;
    }
}
